---
version: '3.9'

name: btcpayserver
services:
  nginx:
    restart: unless-stopped
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - 11180:80
      - 11443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - tor_servicesdir:/var/lib/tor/hidden_services
      - nginx_certs:/etc/nginx/certs:ro
  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.8
    container_name: nginx-gen
    environment:
      DEFAULT_HOST: none
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - tor_servicesdir:/var/lib/tor/hidden_services
      - nginx_certs:/etc/nginx/certs:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s nginx.tmpl /etc/nginx/conf.d/default.conf
  btcpayserver:
    restart: unless-stopped
    image: btcpayserver/btcpayserver:1.10.2
    container_name: btcpayserver
    expose:
      - 49392
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpayservertestnet
      BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorertestnet
      BTCPAY_NETWORK: testnet
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: /
      BTCPAY_SSHCONNECTION: root@host.docker.internal
      BTCPAY_SSHTRUSTEDFINGERPRINTS: abc
      BTCPAY_SSHKEYFILE: file://...
      BTCPAY_SSHAUTHORIZEDKEYS: abc
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: true
      BTCPAY_CHAINS: btc
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc
      BTCPAY_BTCEXTERNALSPARK: server=/spark/btc/;cookiefile=/etc/clightning_bitcoin_spark/.cookie
      BTCPAY_BTCEXTERNALCHARGE: server=/lightning-charge/btc/;cookiefilepath=/etc/clightning_bitcoin_charge/.cookie
      BTCPAY_BTCEXTERNALRTL: server=/rtl/api/authenticate/cookie;cookiefile=/etc/clightning_bitcoin_rtl/.cookie
      BTCPAY_BTCEXTERNALCLIGHTNINGREST: server=/clightning-rest/btc;macaroonfilepath=/etc/clightning_bitcoin_rest_certs/access.macaroon;macaroondirectorypath=/etc/clightning_bitcoin_rest_certs
      HIDDENSERVICE_NAME: BTCPayServer
      HIDDENSERVICE_REVERSEPROXY: nginx
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_SOCKSENDPOINT: tor:9050
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: btcpay.example.com
      VIRTUAL_HOST_NAME: btcpay
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: btcpay.example.com
      LETSENCRYPT_EMAIL: btcpay@example.com
    volumes:
      - btcpay_datadir:/datadir
      - nbxplorer_datadir:/root/.nbxplorer
      - btcpay_pluginsdir:/root/.btcpayserver/Plugins
      - clightning_bitcoin_datadir:/etc/clightning_bitcoin
      - clightning_bitcoin_spark:/etc/clightning_bitcoin_spark
      - clightning_bitcoin_charge:/etc/clightning_bitcoin_charge
      - clightning_bitcoin_rtl_datadir:/etc/clightning_bitcoin_rtl
      - clightning_bitcoin_rest_certsdir:/etc/clightning_bitcoin_rest_certs
      - tor_servicesdir:/var/lib/tor/hidden_services
      - tor_torrcdir:/usr/local/etc/tor/
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:25.0
    environment:
      BITCOIN_NETWORK: testnet
      CREATE_WALLET: false
      BITCOIN_WALLETDIR: /walletdata
      BITCOIN_EXTRA_ARGS: |-
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500

        prune=50000
        onion=tor:9050
        # rpcuser=btcrpc
        # rpcpassword=btcpayserver4ever
        # We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
        # Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped.
        rpcauth=btcrpc:a6a5d29a3f44f02e4cd8cabb5b10a234$$ab6152915515f6a9cca806d2ab5f0e2794c346ba74f812c61e48241d523778b8

        mempoolfullrbf=1
      HIDDENSERVICE_NAME: BTC-P2P,BTC-RPC
      BTC-P2P_HIDDENSERVICE_VIRTUAL_PORT: 8333
      BTC-P2P_HIDDENSERVICE_PORT: 39388
      BTC-RPC_HIDDENSERVICE_VIRTUAL_PORT: 8332
      BTC-RPC_HIDDENSERVICE_PORT: 43782
    expose:
      - 43782
      - 39388
    volumes:
      - bitcoin_wallet_datadir:/data
      - bitcoin_wallet_datadir:/walletdata
      - tor_datadir:/home/tor/.tor
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.3.64
    expose:
      - 32838
    environment:
      NBXPLORER_NETWORK: testnet
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorertestnet
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_CHAINS: btc
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
      - nbxplorer_datadir:/datadir
      - bitcoin_wallet_datadir:/root/.bitcoin
  postgres:
    restart: unless-stopped
    image: btcpayserver/postgres:13.10
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_datadir:/var/lib/postgresql/data
volumes:
  nginx_conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/nginx_conf
  nginx_vhost:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/nginx_vhost
  nginx_html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/nginx_html
  nginx_certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/nginx_certs
  btcpay_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/btcpay_datadir
  btcpay_pluginsdir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/btcpay_pluginsdir
  bitcoin_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/bitcoin_datadir
  bitcoin_wallet_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/bitcoin_wallet_datadir
  clightning_bitcoin_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/clightning_bitcoin_datadir
  clightning_bitcoin_spark:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/clightning_bitcoin_spark
  clightning_bitcoin_charge:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/clightning_bitcoin_charge
  clightning_bitcoin_rtl_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/clightning_bitcoin_rtl_datadir
  clightning_bitcoin_rest_certsdir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/clightning_bitcoin_rest_certsdir
  tor_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/tor_datadir
  tor_torrcdir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/tor_torrcdir
  tor_servicesdir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/tor_servicesdir
  nbxplorer_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/nbxplorer_datadir
  postgres_datadir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /DATA/AppData/$AppID/postgres_datadir
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: btcpayserver
  description:
    en_us: Start Accepting Bitcoin Payments With 0% Fees & No Third-party. BTCPay Server is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant and free.
  tagline:
    en_us: Accept Bitcoin payments. Free, open-source & self-hosted, Bitcoin payment processor.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/f4bio/CasaOS-AppStore@develop/Apps/BTCPayServer/home_screenshot.png
  developer: BTCPayServer
  author: f4bio
  icon: https://cdn.jsdelivr.net/gh/f4bio/CasaOS-AppStore@develop/Apps/BTCPayServer/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/f4bio/CasaOS-AppStore@develop/Apps/BTCPayServer/thumbnail.png
  title:
    en_us: BTCPayServer
  category: Utilities
  port_map: "80"
